name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read
      actions: read
      checks: read
      deployments: read
      issues: read
      packages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Extract version from tag
        id: get_version
        run: |
          # Remove 'v' prefix if present and set as version
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update package __version__ definitions
        run: |
          sed -i 's|__version__ = ".*"|__version__ = "${{ steps.get_version.outputs.version }}"|' src/vsixget/__init__.py
          sed -i 's|__version__ = ".*"|__version__ = "${{ steps.get_version.outputs.version }}"|' src/vsixget/downloader.py
          echo "Updated package versions:"
          grep -n '__version__ = ' src/vsixget/__init__.py src/vsixget/downloader.py

      - name: Build package
        run: |
          python -m build

      - name: Check package
        run: |
          python -m twine check dist/*
          echo "Package contents:"
          ls -la dist/
          echo "Package metadata:"
          python -m twine check dist/* --strict

      - name: Debug trusted publisher claims
        run: |
          echo "=== TRUSTED PUBLISHER CONFIGURATION NEEDED ==="
          echo "Owner: jeremiah-k"
          echo "Repository name: vsixget"
          echo "Workflow filename: pypi-publish.yml"
          echo "Environment name: Release"
          echo ""
          echo "=== CURRENT GITHUB CONTEXT ==="
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Environment: Release"
          echo "Workflow: .github/workflows/pypi-publish.yml"
          echo ""
          echo "Expected sub claim: repo:jeremiah-k/vsixget:environment:Release"
          echo "Expected workflow_ref: jeremiah-k/vsixget/.github/workflows/pypi-publish.yml@${{ github.ref }}"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
          attestations: false
